"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import TextLogo from "@/components/shared/TextLogo";
import SideBar from "@/components/shared/Sidebar";
import Modal from "@/components/shared/Modal/Modal";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });
//
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"
          rel="stylesheet"
        />
      </head>

      <body className="flex w-screen flex-col">
        <QueryClientProvider client={queryClient}>
          <SideBar />
          <Modal />

          <header className="sticky top-0 z-50 flex h-16 w-screen items-center justify-between bg-gray-900">
            <TextLogo className="mx-auto" />
          </header>

          <main className="relative flex h-screen-minus-header w-screen flex-col justify-between overflow-y-hidden bg-sky-900">
            {children}
          </main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
